static const char *osprey_file =
"import nds\n"
"# import os\n"
"\n"
"\n"
"\n"
"KEY_RIGHT = (1 << 4)   # Keypad RIGHT button.\n"
"KEY_LEFT  = (1 << 5)   # Keypad LEFT button.\n"
"KEY_UP    = (1 << 6)   # Keypad UP button.\n"
"KEY_DOWN  = (1 << 7)   # Keypad DOWN button.\n"
"KEY_R     = (1 << 8)   # Right shoulder button.\n"
"KEY_L     = (1 << 9)   # Left shoulder button.\n"
"KEY_X     = (1 << 10)  # Keypad X button.\n"
"while 2>1:\n\n"
"   nds.swiWaitForVBlank()\n\n"
"   nds.scanKeys()\n\n"
"   keys = nds.keysDown()\n\n"
"   if (keys == KEY_UP):\n\n"
"       print('up!')\n\n"
"   if (keys == KEY_DOWN):\n\n"
"       print('down!')\n"
"\n"
"\n"
"\n"
;